#!/bin/bash
# source /opt/packages/anaconda3-2024.10-1/etc/profile.d/conda.sh

#SBATCH -p RM-shared
#SBATCH -t 24:00:00
#SBATCH --mem=6G
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --account bio230007p
#SBATCH -J liver_halper
#SBATCH -e /ocean/projects/bio230007p/jzhao15/project/map_results/liver_run.err
#SBATCH -o /ocean/projects/bio230007p/jzhao15/project/map_results/liver_run.out
#SBATCH --export=ALL

#echo commands to stdout
set -x

bash halper_map_peak_orthologs.sh \
  -b /ocean/projects/bio230007p/jzhao15/project/map_results/Liver_results/HumanLiver_to_MouseLiver/idr.conservative_peak.narrowPeak \
  -o /ocean/projects/bio230007p/jzhao15/project/map_results/Liver_results/HumanLiver_to_MouseLiver \
  -s Human \
  -t Mouse \
  -c /ocean/projects/bio230007p/ikaplow/Alignments/10plusway-master.hal

