#!/bin/bash
#SBATCH --job-name=overlap_liver
#SBATCH --output=overlap_liver.out
#SBATCH --error=overlap_liver.err
#SBATCH --time=01:00:00
#SBATCH --partition=debug
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --mem=4GB

module load bedtools

bedtools intersect \
    -a /ocean/projects/bio230007p/rammohan/project/map_results/Liver_results/HumanLiver_to_MouseLiver/idr.conservative_peak.HumanToMouse.HALPER.narrowPeak \
    -b /ocean/projects/bio230007p/rammohan/project/map_results/Liver_results/MouseLiver_peaks.bed \
    -wa > /ocean/projects/bio230007p/rammohan/project/map_results/Liver_results/HumanLiver_to_MouseLiver/halper_liver_overlap.bed
